name: CI

on:
  pull_request:
  push:
    branches: 
      - master
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Eslint
      run: npm run eslint
    - name: Test
      run: npm run test
    - name: Build and Deploy
      run: npm run deploy
